openapi: 3.0.0
info:
  title: Simple Ping API
  description: API de test pour vérifier le fonctionnement de Swagger dans IntelliJ
  version: 1.0.0

servers:
  - url: http://localhost:8000

paths:
  /ping:
    get:
      summary: Test de connexion
      description: Retourne "pong" si l’API fonctionne.
      responses:
        '200':
          description: Succès - retourne "pong"
          content:
            text/plain:
              schema:
                type: string
                example: pong
